# --------------------------------------------------------------------------------
# Average Sweep Analysis Tool
# Author: Natalia Andrea Corvalan
# Version: 1.0.0
# DOI = "xxxxx/zenodo.XXXXXXX"
# --------------------------------------------------------------------------------

import os
import sys
from datetime import datetime
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import pyabf
from numpy.fft import fft, ifft, fftfreq


# ==============================================================================
# SOFTWARE METADATA
# ==============================================================================

SOFTWARE_NAME = "Average Sweep Analysis Tool: Automated Gaussian-Filtered Sweep Averaging from ABF Files [Computer software]"
AUTHOR = "Natalia Andrea Corvalan"
VERSION = "1.0.0"
DOI = "xxxxx/zenodo.XXXXXXX"
REPOSITORY_LINK = "https://dacytar.mincyt.gob.ar/"


def splash_screen():
    print("\n" + "=" * 70)
    print(f"{SOFTWARE_NAME} - Version {VERSION}")
    print(f"Author: {AUTHOR}")
    print("\nIf you use this software, please cite it as:")
    print("\n" + f"{AUTHOR} ({datetime.now().year}).")
    print(f"{SOFTWARE_NAME}(Version {VERSION}).")
    print(f"DOI: {DOI}")
    print("=" * 70 + "\n")


# ==============================================================================
# SIGNAL PROCESSING
# ==============================================================================

def gaussian_lowpass_filter(signal, fs, cutoff_hz):
    n = len(signal)
    freqs = fftfreq(n, d=1/fs)
    spectrum = fft(signal)
    gauss = np.exp(-0.5 * (freqs / cutoff_hz) ** 2)
    filtered_spectrum = spectrum * gauss
    return np.real(ifft(filtered_spectrum))


# ==============================================================================
# MAIN PROGRAM
# ==============================================================================

def main():

    splash_screen()

    cutoff = float(input(
        "Enter cutoff frequency (-3 dB) in Hz for the Gaussian lowpass filter: "
    ))

    folder_path = os.getcwd()
    abf_files = [f for f in os.listdir(folder_path) if f.endswith(".abf")]

    if not abf_files:
        print("No ABF files found in folder.")
        sys.exit(1)

    first_abf = pyabf.ABF(os.path.join(folder_path, abf_files[0]))
    channel_count = first_abf.channelCount

    print("\nAvailable channels:\n")
    for ch in range(channel_count):
        first_abf.setSweep(0, channel=ch)
        print(f"Channel {ch}: {first_abf.sweepLabelY}")

    selected_channel = int(input("\nEnter channel number to process: "))

    if selected_channel < 0 or selected_channel >= channel_count:
        print("Invalid channel selection.")
        sys.exit(1)

    print(f"\nProcessing Channel {selected_channel}...\n")

    raw_sweeps_list = []
    filtered_sweeps_list = []
    headers_raw = []
    headers_filtered = []

    axis_label_x = ""
    axis_label_y = ""

    for abf_file in abf_files:
        abf_path = os.path.join(folder_path, abf_file)
        abf = pyabf.ABF(abf_path)
        fs = abf.dataRate

        for sweep_num in range(abf.sweepCount):

            abf.setSweep(sweep_num, channel=selected_channel)

            raw = abf.sweepY
            filtered = gaussian_lowpass_filter(raw, fs, cutoff)
            time = abf.sweepX

            if not axis_label_x:
                axis_label_x = abf.sweepLabelX
            if not axis_label_y:
                axis_label_y = abf.sweepLabelY

            raw_sweeps_list.append(raw)
            filtered_sweeps_list.append(filtered)

            headers_raw.extend([
                f"{axis_label_x}_{abf_file}_Sweep{sweep_num}",
                f"{axis_label_y}_{abf_file}_Sweep{sweep_num}"
            ])

            headers_filtered.extend([
                f"{axis_label_x}_{abf_file}_Sweep{sweep_num}",
                f"{axis_label_y}_{abf_file}_Sweep{sweep_num}"
            ])

    raw_array = np.column_stack([
        np.column_stack((time, sweep)) for sweep in raw_sweeps_list
    ])

    filtered_array = np.column_stack([
        np.column_stack((time, sweep)) for sweep in filtered_sweeps_list
    ])

    mean_sweep = np.mean(filtered_array[:, 1::2], axis=1)

    metadata_block = (
        f"# Generated by {SOFTWARE_NAME}\n"
        f"# Version: {VERSION}\n"
        f"# Author: {AUTHOR}\n"
        f"# DOI: {DOI}\n"
        f"# Repository: {REPOSITORY_LINK}\n"
        f"# Date: {datetime.now()}\n"
    )

    np.savetxt(
        "average_sweep.txt",
        np.column_stack((time, mean_sweep)),
        delimiter="\t",
        header=metadata_block +
               f"{axis_label_x}\tAverage_Filtered_{axis_label_y}",
        comments=""
    )

    np.savetxt(
        "individual_sweeps_raw.txt",
        raw_array,
        delimiter="\t",
        header=metadata_block + "\t".join(headers_raw),
        comments=""
    )

    np.savetxt(
        "individual_sweeps_filtered.txt",
        filtered_array,
        delimiter="\t",
        header=metadata_block + "\t".join(headers_filtered),
        comments=""
    )

    plt.figure(figsize=(10, 5))

    for sweep in filtered_array[:, 1::2].T:
        plt.plot(time, sweep, alpha=0.3, linewidth=0.8)

    plt.plot(time, mean_sweep,
             label="Average Sweep",
             linewidth=2)

    plt.xlabel(axis_label_x)
    plt.ylabel(axis_label_y)
    plt.title(f"{SOFTWARE_NAME} - Channel {selected_channel}")
    plt.legend()
    plt.tight_layout()

    plt.savefig("comparative_average_sweep.png", dpi=300)

    plt.show(block=False)
    plt.pause(0.1)


    print("\nAll files successfully generated:")
    print("- average_sweep.txt")
    print("- individual_sweeps_raw.txt")
    print("- individual_sweeps_filtered.txt")
    print("- comparative_average_sweep.png")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print("\nUnexpected error occurred:")
        print(str(e))
    finally:
        input("\nPress Enter to exit...")

